### ISSUE TITLE
How to get an instance of the current editor in order to set and get values from it?

### ISSUE THREAD

**Issue by cesarvega** [rodikh/angular-json-editor#16]
Hi, I was wondering if you know how to get an instance of the current editor so I can use the methods
editor.getValue();
editor.setValue({
    name: "John Smith"
}); ?

**Comment by rodikh** [comment]
You need to pass a buttonsController in order to gain access to the editor object.
see the example: 
https://github.com/rodikh/angular-json-editor/blob/master/demo/app.js#L51
https://github.com/rodikh/angular-json-editor/blob/master/demo/index.html#L19
This will allow you to access it using $scope.editor.setValue/getValue

Otherwise, you can use the onChange method to get the form's value whenever it's changed, but not to set the value at any time.
